CREATE TABLE OLIVE_HEAT_MAP 
(
  ID NUMBER(18, 0) NOT NULL 
, X_AXIS NUMBER(18, 0) NOT NULL 
, Y_AXIS NUMBER(18, 0) NOT NULL 
, IMAGE_IDENTIFIER VARCHAR2(64 BYTE) NOT NULL 
, CREATED_BY VARCHAR2(64 BYTE) 
, CREATED_DATE DATE NOT NULL 
, CONSTRAINT SYS_C009701 PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);